[project]
name = "buttercookie"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "buttercookiegh", email = "israt.bushra.eee@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.14.0",
]

[tool.maturin]
module-name = "buttercookie._core"
python-packages = ["buttercookie"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[tool.uv.workspace]
members = [
    "difftest",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
